version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - gen_ai_kickstarter_net
    volumes:
      - /ollama_data:/root/.ollama

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    environment: 
      - WEBUI_AUTH=false # never ever use in production environment 
      - OLLAMA_BASE_URL=http://ollama:11434
    ports:
      - "3000:8080"
    depends_on:
      - ollama
    networks:
      - gen_ai_kickstarter_net
    volumes: 
      - /open-webui:/app/backend/data

networks:
  gen_ai_kickstarter_net: 
    driver: bridge